AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates an API for the project EBS
  Last Modified: 14 October 2018
  Author: Exec <aerioeus@gmail.com>
Metadata: {}

Parameters:
  Owner:
    Description: Team or Individual Name Responsible for the Stack.
    Type: String
    Default: Andreas Rose

  Project:
    Description: Enter Project Name.
    Type: String
    Default: invoicegenerator

  Subproject:
    Description: Enter Project Name.
    Type: String
    Default: ebs

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    ConstraintDescription: Specify either Dev or Prod

  ApiKeySourceType:
    Description: Setup for the ApiKeySourceType
    Type: String
    Default: HEADER

  binaryMediaType1:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "*~1*"

  binaryMediaType2:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "image~1png"

  binaryMediaType3:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "image~1jpeg"

  binaryMediaType4:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "image~1gif"

  binaryMediaType5:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "application~1pdf"

  binaryMediaType6:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "application~1json"

  binaryMediaType7:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "application~1xml"

  binaryMediaType8:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "text~1html"

  binaryMediaType8:
    Description: binary media type that is supported by the RestApi resource
    Type: String
    Default: "text~1plain"

  minimumCompressionSize:
    Description: >
      integer that is used to enable compression (with non-negative between 0
      and 10485760 (10M) bytes, inclusive) or disable compression (with a null value) on an API
    Type: String
    Default: 1048576

  EndpointConfiguration:
    Description: A list of the endpoint types of the domain name
    Type: String
    Default: EDGE
    AllowedValues:
      - EDGE
      - REGIONAL
    ConstraintDescription: Specify either EDGE or REGIONAL

  RestApiName:
    Description: Name for the API Gateway RestApi
    Type: String
    Default: contactsapi

  BasePath:
    Description: >
      custom domain name for your API in Amazon API Gateway
      Uppercase letters are not supported
    Type: String
    Default: contacts

  IdentitySource:
    Description: The source of the identity in an incoming request
    Type: String
    Default: Authorization

  ThrottlingBurst:
    Description: number of burst requests per second that API Gateway permits across all APIs, stages, and methods in an AWS account
    Type: Number
    Default: 200

  ThrottlingRate:
    Description: number of steady-state requests per second that API Gateway permits across all APIs, stages, and methods in an AWS account
    Type: Number
    Default: 500

  Stagename:
    Description: name of the stage, which API Gateway uses as the first path segment in the invoked Uniform Resource Identifier (URI)
    Type: String
    Default: v1

  APIDomain:
    Description: DomainName for the API
    Type: String

  APIClientCertificateName:
    Description: client certificate that Amazon API Gateway (API Gateway) uses to configure 
      client-side SSL authentication for sending requests to the integration endpoint
    Type: String

Resources:
  Api1:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: !Sub Api for ${BasePath}-Resource for EBS
      Name: !Ref RestApiName
      ApiKeySourceType: !Ref ApiKeySourceType
      BinaryMediaTypes:
        - !Ref binaryMediaType1
        - !Ref binaryMediaType2
        - !Ref binaryMediaType3
        - !Ref binaryMediaType4
        - !Ref binaryMediaType5
        - !Ref binaryMediaType6
        - !Ref binaryMediaType7
        - !Ref binaryMediaType8
      Body:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub "s3://${AWS::AccountId}-${Project}-swaggerapis/contacts_swagger.yaml"
      EndpointConfiguration:
        Types:
          - !Ref EndpointConfiguration
      FailOnWarnings: true
      MinimumCompressionSize: !Ref minimumCompressionSize

  SubdomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref BasePath
      DomainName:  !Ref APIDomain
      RestApiId: !Ref Api1
      Stage: !Ref ApiStage

# we import a COGNITO_USER_POOLS authorizer with an OpenAPI definition file
#  Authorizer:
#    Type: AWS::ApiGateway::Authorizer
#    Properties:
#      AuthorizerResultTtlInSeconds: "300"
#      Type: COGNITO_USER_POOLS
#      IdentitySource: !Sub method.request.header.${IdentitySource}
#      Name: !Sub ${BasePath}-Api-Authorizer
#      RestApiId: !Ref Api1
#      ProviderARNs:
#        - Fn::ImportValue: !Sub ${EnvironmentName}-${Project}-UserPoolARN

  # a "stage" represents a unique identifier for a particular version of a deployed RestApi like "dev", "test", "prod" etc
  # if the stage is assigned the deployment then that is callable by users
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      Description: !Sub ${EnvironmentName}-Stage
      StageName: !Ref Stagename
      RestApiId: !Ref Api1
      DeploymentId: !Ref ApiDeployment
      ClientCertificateId:  !Ref APIClientCertificateName
      AccessLogSetting:
        DestinationArn:
          Fn::ImportValue: !Sub ${EnvironmentName}-ApiLogGroupARN
        Format: $context.error.message
          $context.error.messageString
          $context.identity.user
          $context.requestId
          $context.requestTime
          $context.resourceId
          $context.stage
          $context.responseLatency
          $context.identity.userArn
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: true
          LoggingLevel: INFO
      TracingEnabled: true

  # deploys the Api API to a stage specified in the stage resource
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Deployment API
      RestApiId: !Ref Api1

  # creates a unique key that you can distribute to clients
  ApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ApiStage
    Properties:
      Name: ApiKey
      Description: CloudFormation API Key V1
      Enabled: true
      StageKeys:
        - RestApiId: !Ref Api1
          StageName: !Ref ApiStage

  # creates a usage plan to enforce throttling and quota
  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      Description: Customer usage plan
      ApiStages:
        - ApiId: !Ref Api1
          Stage: !Ref ApiStage
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: !Ref ThrottlingBurst
        RateLimit: !Ref ThrottlingRate
      UsagePlanName: Invoiceapp-usageplan

  usagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  RestApiId:
    Description: returns the RestApi ID
    Value: !Ref Api1

  RootResourceId:
    Description: returns the root resource ID for a RestApi resource
    Value: !GetAtt Api1.RootResourceId

  RootUrl:
    Description: Root URL of the API gateway
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: Api1
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com"

  ApiDomain:
    Description: Domain of the API gateway
    Value:
      Fn::Join:
        - ""
        - - Ref: Api1
          - ".execute-api."
          - Ref: AWS::Region
          - ".amazonaws.com"

  ApiKeyId:
    Description: returns the API key ID
    Value: !Ref ApiKey

  ApiStageName:
    Description: returns the name of the stage
    Value: !Ref ApiStage