AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template createsa lambda function for the project Invoicegenerator App
  Last Modified: 14 October 2018
  Author: Exec <aerioeus@gmail.com>

Metadata: {}

Parameters:
  Owner:
    Description: Enter Team or Individual Name Responsible for the Stack.
    Type: String
    Default: Andreas Rose

  Project:
    Description: Enter Project Name.
    Type: String
    Default: invoicegenerator

  Subproject:
    Description: Enter Project Name.
    Type: String
    Default: ebs

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod
    ConstraintDescription: Specify either Dev or Prod

Resources:
  # Lambda Function API
  GreetingLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: A greeting function
      FunctionName: GreetingLambda
#      Code:
#        S3Bucket:
#          Fn::ImportValue: !Sub ${EnvironmentName}-LambdaCodeBucket-Name
#        S3Key: "greeter.zip"
      Code:
        ZipFile:
          Fn::Join:
          - "\n"
          - - "'use strict';"
            - ''
            - "// Greeter Lambda"
            - exports.handler = (event, context, callback) => {
            - "  console.log('Event:', JSON.stringify(event));"
            - "  const name = event.name || 'World';"
            - "  const response = {greeting: `Hello, ${name}!`};"
            - "  callback(null, response);"
            - "};"
      Environment: {}
      KmsKeyArn:
        Fn::ImportValue: !Sub ${EnvironmentName}-InvoicegenKey-CMK-Arn
      MemorySize: 512
      Handler: index.handler
      Role:
        Fn::ImportValue: !Sub ${EnvironmentName}-LambdaExecutionRoleARN
      Runtime: nodejs8.10
      Timeout: 5
      Tags:
        - Key: Name
          Value: API_Lambda

Outputs:
  StackName:
    Description: The Name of the Stack
    Value: !Ref AWS::StackName

  Owner:
    Description: Team or Individual that Owns this Formation.
    Value: !Ref Owner

  Project:
    Description: The project name
    Value: !Ref Project

  Subproject:
    Description: The project name
    Value: !Ref Subproject

  GreetingLambdaARN:
    Description: returns the ARN of the Lambda function
    Value: !GetAtt GreetingLambda.Arn
    Export:
      Name: GreetingLambdaARN

  GreetingLambdaName:
    Description: returns the NAME of the Lambda function
    Value: !Ref GreetingLambda
    Export:
      Name: !Sub ${EnvironmentName}-${Project}-GreetingLambdaNAME